### ISSUE TITLE
TensorFlow 1 and python 3.8

### ISSUE THREAD

**Issue by AlexGKim** [VMBoehm/PAE#1]
The dependency of this package on TensorFlow 1 means that it can't be run on python 3.8.  Are there plans to upgrade to TF2?

**Comment by VMBoehm** [comment]
I have a code version that runs on tf2. I'll clean it up and submit it asap

**Comment by AlexGKim** [comment]
Thanks!

**Comment by VMBoehm** [comment]
the code on the tf2 branch should now run with tensorflow 2, the instructions are the same as for the tf1 version. The density estimation notebooks were already in tf2, I only changed the code for the Auto-Encoder. Would you like me to add support to the SDSS spectra that you linked to in your talk? I'm wondering if it might be better to just start an ipython notebook with a simple Auto-Encoder to get a first feel for that kind of data. The python package in this repo is very powerful, but might be a little black boxy to start with.

**Comment by AlexGKim** [comment]
I got PAE code installed on cori at NERSC and a working kernel for a jupyter notebook.  The desi data pipeline runs on python 3.8 so the upgrade to tf2 makes my life a lot easier!

I plan to start a jupyter notebook (tomorrow?) starting with the data I/O. Are you setup to work on Cori?   The SDSS data are on spinning disk at NERSC, /global/project/projectdirs/cosmo/data/sdss/dr16/sdss/spectro/data.  The data are managed in different directories according to the date of observation, and in a fits file per exposure.

Should we close this issue and talk via Slack or email?

**Comment by VMBoehm** [comment]
great! I'll close the issue and we can return to slack. I am set up to work on Cori and the Cori GPU nodes.
